"""
The fixed texts the `bench` op's suite="tokenizer" measures compression on, and the prompts of
suite="sample". Ported from our nanochat fork's scripts/tok_eval.py and scripts/base_eval.py. The Korean
sample is stored with \\u escapes so this file stays ASCII-clean of non-Latin scripts (the repo's
English-only rule); the rest is as it was.
"""

TEXTS = {
    "news": '(Washington, D.C., July 9, 2025)- Yesterday, Mexico’s National Service of Agro-Alimentary Health, Safety, and Quality (SENASICA) reported a new case of New World Screwworm (NWS) in Ixhuatlan de Madero, Veracruz in Mexico, which is approximately 160 miles northward of the current sterile fly dispersal grid, on the eastern side of the country and 370 miles south of the U.S./Mexico border. This new northward detection comes approximately two months after northern detections were reported in Oaxaca and Veracruz, less than 700 miles away from the U.S. border, which triggered the closure of our ports to Mexican cattle, bison, and horses on May 11, 2025.\n\nWhile USDA announced a risk-based phased port re-opening strategy for cattle, bison, and equine from Mexico beginning as early as July 7, 2025, this newly reported NWS case raises significant concern about the previously reported information shared by Mexican officials and severely compromises the outlined port reopening schedule of five ports from July 7-September 15. Therefore, in order to protect American livestock and our nation’s food supply, Secretary Rollins has ordered the closure of livestock trade through southern ports of entry effective immediately.\n\n“The United States has promised to be vigilant — and after detecting this new NWS case, we are pausing the planned port reopening’s to further quarantine and target this deadly pest in Mexico. We must see additional progress combatting NWS in Veracruz and other nearby Mexican states in order to reopen livestock ports along the Southern border,” said U.S. Secretary of Agriculture Brooke L. Rollins. “Thanks to the aggressive monitoring by USDA staff in the U.S. and in Mexico, we have been able to take quick and decisive action to respond to the spread of this deadly pest.”',
    "korean": '\uc815\uc9c1\ud55c \uc0ac\uc2e4 \uc704\uc5d0, \uacf5\uc815\ud55c \uc2dc\uc120\uc744 \ub354\ud558\ub2e4\nHerald Korea Times\n\n\ud5e4\ub7f4\ub4dc\ucf54\ub9ac\uc544\ud0c0\uc784\uc988\ub294 \uc815\uce58, \uacbd\uc81c, \uc0ac\ud68c, \ubb38\ud654 \ub4f1 \ud55c\uad6d \uc0ac\ud68c \uc804\ubc18\uc758 \uc8fc\uc694 \uc774\uc288\ub97c \uc2ec\ub3c4 \uc788\uac8c \ub2e4\ub8e8\ub294 \uc885\ud569 \uc628\ub77c\uc778 \uc2e0\ubb38\uc0ac\uc785\ub2c8\ub2e4.\n\n\uc6b0\ub9ac\ub294 \ub2e8\uc21c\ud788 \ub274\uc2a4\ub97c \uc804\ub2ec\ud558\ub294 \uac83\uc774 \uc544\ub2c8\ub77c, \uc0ac\uc2e4(Fact)\uc5d0 \uae30\ubc18\ud55c \uc591\uce21\uc758 \uc2dc\uac01\uc744 \uade0\ud615 \uc788\uac8c \uc870\uba85\ud558\uba70, \ub3c5\uc790 \uc5ec\ub7ec\ubd84\uc774 \uc2a4\uc2a4\ub85c \ud310\ub2e8\ud560 \uc218 \uc788\ub294 ‘\uc815\ubcf4\uc758 \uade0\ud615’\uc744 \uc81c\uacf5\ud569\ub2c8\ub2e4.\n\n\ud55c\uad6d \uc5b8\ub860\uc758 \uc624\ub79c \ubb38\uc81c\ub85c \uc9c0\uc801\ub418\uc5b4 \uc628 \uc815\uce58\uc801 \ud3b8\ud5a5, \uc774\ub150\uc801 \uc65c\uace1\uc5d0\uc11c \ubc97\uc5b4\ub098\n\uc624\uc9c1 \uc815\uc9c1\ud568\uacfc \uacf5\uc815\ud568\uc744 \uc6d0\uce59\uc73c\ub85c \uc0bc\ub294 \uc5b8\ub860\uc744 \uc9c0\ud5a5\ud569\ub2c8\ub2e4.\n\uc5b4\ub290 \ud55c\ucabd\uc758 \uc8fc\uc7a5\ub9cc\uc744 \ud655\ub300\ud558\uac70\ub098 \uac10\ucd94\uc9c0 \uc54a\uace0,\n**\ubaa8\ub4e0 \uc7c1\uc810\uc5d0 \ub300\ud574 ‘\ubb34\uc5c7\uc774 \uc7c1\uc810\uc778\uc9c0’, ‘\ub204\uac00 \ubb34\uc5c7\uc744 \uc8fc\uc7a5\ud558\ub294\uc9c0’, ‘\uc0ac\uc2e4\uc740 \ubb34\uc5c7\uc778\uc9c0’**\ub97c \uba85\ud655\ud788 \uc804\ub2ec\ud558\ub294 \ub370 \uc9d1\uc911\ud569\ub2c8\ub2e4.',
    "code": 'class BasicTokenizer(Tokenizer):\n\n    def __init__(self):\n        super().__init__()\n\n    def train(self, text, vocab_size, verbose=False):\n        assert vocab_size >= 256\n        num_merges = vocab_size - 256\n\n        # input text preprocessing\n        text_bytes = text.encode("utf-8") # raw bytes\n        ids = list(text_bytes) # list of integers in range 0..255\n\n        # iteratively merge the most common pairs to create new tokens\n        merges = {} # (int, int) -> int\n        vocab = {idx: bytes([idx]) for idx in range(256)} # int -> bytes\n        for i in range(num_merges):\n            # count up the number of times every consecutive pair appears\n            stats = get_stats(ids)\n            # find the pair with the highest count\n            pair = max(stats, key=stats.get)\n            # mint a new token: assign it the next available id\n            idx = 256 + i\n            # replace all occurrences of pair in ids with idx\n            ids = merge(ids, pair, idx)\n            # save the merge\n            merges[pair] = idx\n            vocab[idx] = vocab[pair[0]] + vocab[pair[1]]\n            # prints\n            if verbose:\n                print(f"merge {i+1}/{num_merges}: {pair} -> {idx} ({vocab[idx]}) had {stats[pair]} occurrences")',
    "math": '\\documentclass[12pt]{article}\n\\usepackage{amsmath,amsthm,amssymb}\n\\usepackage[margin=1in]{geometry}\n\n\\newtheorem{theorem}{Theorem}\n\\newtheorem*{remark}{Remark}\n\n\\begin{document}\n\n\\begin{center}\n{\\Large A Cute Identity: The Sum of Cubes is a Square}\n\\end{center}\n\n\\begin{theorem}\nFor every integer $n \\ge 1$,\n\\[\n\\sum_{k=1}^{n} k^{3} \\;=\\; \\left(\\frac{n(n+1)}{2}\\right)^{2}.\n\\]\n\\end{theorem}\n\n\\begin{proof}[Proof 1 (Induction)]\nLet $S(n) = \\sum_{k=1}^{n} k^3$. For $n=1$, $S(1)=1=(1\\cdot 2/2)^2$, so the base case holds.\n\nAssume $S(n)=\\big(\\tfrac{n(n+1)}{2}\\big)^2$ for some $n\\ge 1$.\nThen\n\\[\nS(n+1)\n= S(n) + (n+1)^3\n= \\left(\\frac{n(n+1)}{2}\\right)^2 + (n+1)^3.\n\\]\nFactor out $(n+1)^2$:\n\\[\nS(n+1)\n= (n+1)^2\\left( \\frac{n^2}{4} + (n+1) \\right)\n= (n+1)^2\\left( \\frac{n^2 + 4n + 4}{4} \\right)\n= (n+1)^2\\left( \\frac{(n+2)^2}{4} \\right).\n\\]\nThus\n\\[\nS(n+1)=\\left(\\frac{(n+1)(n+2)}{2}\\right)^2,\n\\]\nwhich matches the claimed formula with $n$ replaced by $n+1$. By induction, the identity holds for all $n\\ge 1$.\n\\end{proof}\n\n\\begin{proof}[Proof 2 (Algebraic telescoping)]\nRecall the binomial identity\n\\[\n(k+1)^4 - k^4 = 4k^3 + 6k^2 + 4k + 1.\n\\]\nSumming both sides from $k=0$ to $n$ telescopes:\n\\[\n(n+1)^4 - 0^4\n= \\sum_{k=0}^{n}\\big(4k^3 + 6k^2 + 4k + 1\\big)\n= 4\\sum_{k=1}^{n}k^3 + 6\\sum_{k=1}^{n}k^2 + 4\\sum_{k=1}^{n}k + (n+1).\n\\]\nUsing the standard sums\n\\[\n\\sum_{k=1}^{n}k = \\frac{n(n+1)}{2}\n\\quad\\text{and}\\quad\n\\sum_{k=1}^{n}k^2 = \\frac{n(n+1)(2n+1)}{6},\n\\]\nsolve for $\\sum_{k=1}^{n}k^3$ to get\n\\[\n\\sum_{k=1}^{n}k^3 = \\left(\\frac{n(n+1)}{2}\\right)^2.\n\\]\n\\end{proof}\n\n\\begin{remark}\nGeometrically, the identity says: ``adding up $1^3,2^3,\\dots,n^3$ builds a perfect square’’—namely the square of the $n$th triangular number. This is why one sometimes calls it the \\emph{sum-of-cubes is a square} phenomenon.\n\\end{remark}\n\n\\end{document}',
    "science": 'Photosynthesis is a photochemical energy transduction process in which light-harvesting pigment–protein complexes within the thylakoid membranes of oxygenic phototrophs absorb photons and initiate charge separation at the reaction center, driving the linear electron transport chain from water to NADP⁺ via photosystem II, the cytochrome b₆f complex, and photosystem I, concomitantly generating a trans-thylakoid proton motive force utilized by chloroplastic ATP synthase. The light-dependent reactions produce ATP and NADPH, which fuel the Calvin–Benson–Bassham cycle in the stroma, wherein ribulose-1,5-bisphosphate is carboxylated by ribulose-1,5-bisphosphate carboxylase/oxygenase (RuBisCO) to form 3-phosphoglycerate, subsequently reduced and regenerated through a series of enzymatic steps, enabling net assimilation of CO₂ into triose phosphates and ultimately carbohydrates. This process is tightly regulated by photoprotective mechanisms, redox feedback, and metabolite flux, representing a central biochemical pathway coupling solar energy capture to the biosphere’s primary productivity.',
}

SAMPLE_PROMPTS = [
    "The capital of France is",
    "The chemical symbol of gold is",
    "If yesterday was Friday, then tomorrow will be",
    "The opposite of hot is",
    "The planets of the solar system are:",
    "My favorite color is",
    "If 5*x + 3 = 13, then x is",
]
